name: "ChartCraftHub Lint"
run-name: "BUILD - CI Python (${{ github.event_name }})"

on:
  pull_request:
  push:
    branches:
      - trunk

concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

env:
  PYTHON_VERSION: 3.12.1

jobs:
  changes:
    name: 🔄 Check out changes
    runs-on: ubuntu-latest
    timeout-minutes: 1
    permissions:
      pull-requests: read
    outputs:
      changes: ${{ steps.filter.outputs.changes }}
    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
    - name: Check for backend file changes
      uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 #v3.0.2
      id: changes
      with:
        filters: |
          changes:
          - "**.py"
          - "**.ipynb"
  ci:
    name: 🛠️ Setup Python environment
    if: needs.changes.outputs.changes == 'true'
    needs: changes
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python environment
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'
      - name: Install dependencies
        run: make install
      - name: Lint
        run: make lint
      - name: Test
        run: make test
